### ISSUE TITLE
make non abstract wave manager for our level

### ISSUE THREAD

**Issue by herrkrabbe** [herrkrabbe/Programming3TD#20]
the wave manager instance should create dead enemies on begin play and delete them at end play. the enemies must be added to the new enemies queue in begin play after being created.

**Comment by pauliepus** [comment]
So far, Ive created a ConcreteWavemanager, and added empty functions to it.

Trying to figure out how to call the queues and how to de-yeet them.

**Comment by pauliepus** [comment]
Opened new files, made empty Beginplays, endplays etc. 

Haven't found out how to get the queues yet, or how to de-yeet them.
