### ISSUE TITLE
Update AStar

### ISSUE THREAD

**Issue by herrkrabbe** [herrkrabbe/Programming3TD#26]
make AStar include distance in cost

create a constant operator< for GraphNode, which compares GetValue for the graphNodes. The highest result from GetValue should be the greater of the two GraphNodes. this is needed for heap sortning

**Comment by pauliepus** [comment]
bruh, jeg aner ikke hva jeg har gjort, men jeg har gjort noe.

I'm just throwing shit at the wall.

**Comment by herrkrabbe** [comment]
mission complete
