### ISSUE TITLE
bugfix the pathfinding for wave 3

### ISSUE THREAD

**Issue by herrkrabbe** [herrkrabbe/Programming3TD#40]
replicate:
build 3 towers in wve one. on node 2_2, 3_1, and 4_2.
build nothing wave 2
problem in wave 3

**Comment by pauliepus** [comment]
Could not replicate. 

Thought I noticed if I Alt-tab while watching the simulation, the game would glitch out the characters, moving them into eachother etc.

**Comment by Kittel-Watne** [comment]
Wave 1 the enemy walked up, then down in order to reach the goal. 
Before the second round i placed 2 towers on the nodes they chose to walk through. On wave 2 the enemies went down, and then down again walking straight into the tower placed there. 
3rd wave avoided both towers.

**Comment by herrkrabbe** [comment]
Denied

**Comment by Kittel-Watne** [comment]
I was simply suffering from intense skill issue

**Comment by herrkrabbe** [comment]
fr
